### ISSUE TITLE
After 4.0.4: '"fastify-error"' has no exported member 'FastifyErrorConstructor'

### ISSUE THREAD

**Issue by RomaricMourgues** [fastify/fastify-multipart#238]
## 💥 Regression Report

Hi, it seems this PR break after v4.0.3: https://github.com/fastify/fastify-multipart/pull/222 .

Error:

```
node_modules/fastify-multipart/index.d.ts(4,10): error TS2614
Module '"fastify-error"' has no exported member 'FastifyErrorConstructor'. Did you mean to use 'import FastifyErrorConstructor from "fastify-error"' instead?
```

## Last working version

Worked up to version: 4.0.3

Stopped working in version: 4.0.4

## To Reproduce

Just npm install and try to use the library.

## Your Environment

- *node version*: 12
- *fastify version*: 3.9.2
- *os*: Mac, Linux

**Comment by mcollina** [comment]
What version of fastify-error are you using?

cc @fastify/typescript

**Comment by RomaricMourgues** [comment]
Looking at the package-lock.json:
- node_modules/fastify-error: 0.2.0
- node_modules/fastify-multipart/node_modules/fastify-error: 0.3.1

It seems to be an error with my npm, fastify-multipart require fastify-error >=0.3.0 and fastify require fastify-error >=0.2.0. At the end 0.2.0 is installed instead of 0.3.1.
On a clean install with just  `"@types/busboy": "^0.2.3", "fastify": "^3.9.2", "fastify-multipart": "^4.0.6"` it seems to work. We can close the issue.

And if it happens to anyone else, downgrading to 4.0.3 works of course. Or you can force `"fastify-error": ">=0.3.1",` in package.json.

Sorry for the ticket, have a good day!
