### ISSUE TITLE
Upgrading to 2.0.3 build error "has not exported member 'FastifyPlugin'"

### ISSUE THREAD

**Issue by AcidSlide** [fastify/fastify-multipart#136]
## 💥 Regression Report

After upgrading from version 1.0.6 to 2.0.3 receiving build error (using NestJs)

```
> nest build

node_modules/fastify-multipart/index.d.ts:2:10 - error TS2305: Module '"../fastify/fastify"' has no exported member 'FastifyPlugin'.

#2 import { FastifyPlugin } from "fastify";
```

## Last working version

Worked up to version: 1.0.6

Stopped working in version: 2.0.3

## To Reproduce

```
npm run build
```

## Expected behavior

Build/Compile to continue with no errors.

## Your Environment

- *node version*: 10.20.1
- *fastify version*: >=2.0.0
- *os*: Mac
- Using NestJS 7.3.2 framework with @nestjs/platform-fastify

**Comment by AcidSlide** [comment]
sorry closing this, it seems the issue is related with the nestjs/platform-fastify which needs to get updated to v3 of Fastify.
